### ISSUE TITLE
Dereferencing state_ptr seems to be broken

### ISSUE THREAD

**Issue by fkutzner** [Robbepop/state_ptr#4] opened 2017-08-19 11:33 UTC
As of commit 894d894641ac956fdd67b8a8b966ba998d6c79f0, dereferencing state_ptr instances seems to be broken.

Example:
```cpp
int testData = 1;
putl::state_ptr<int> underTest{&testData, 0};
int target = *underTest;
```

When compiling with Apple clang-802.0.42, I get the following error:

```
[...]/state_ptr/include/putl/state_ptr.hpp:263:10: error: reinterpret_cast from rvalue to reference type
      'reference_type' (aka 'int &')
                return reinterpret_cast<reference_type>(get_ptr());
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]/state_ptr/testsrc/state_ptr_tests.cpp:119:18: note: in instantiation of member function
      'putl::state_ptr<int, unsigned long, 2>::operator*' requested here
    int target = *underTest;

```

**Comment by Robbepop** [comment] 2017-08-20 17:30
Thank you very much for the bug report!

I am a bit confused by the compiler error since I thought converting T* to T& should be trivial, however, it seems not to be.
Hopefully my fix did not introduce unintended behaviour that my new test cases couldn't find - it would be awesome if you could review it before we close this issue.

**Comment by fkutzner** [comment] 2017-08-20 20:13
Thanks for tackling this issue so fast :) The new version works fine in my code.

The state_ptr implementation looks safe. I think the the `reinterpret_cast`s in both `operator*()` definitions could be safely removed. There's a note in the standard about situations like this one:

> [ Note: That is, for lvalues, a reference cast `reinterpret_cast<T&>(x)` has the same effect as the conversion `*reinterpret_cast<T*>(&x)` with the built-in & and * operators (and similarly for `reinterpret_cast<T&&>(x)`).  — end note ]

(http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf (Sec. 5.2.10/11); found it via https://stackoverflow.com/a/5924278)

**Comment by Robbepop** [comment] 2017-08-20 23:27
Thank you very much for the link!

- closed

**Closed as completed by Robbepop** 2017-08-20 23:27 UTC
